swupdate-uf-installer-agent: fix error reporting
Fix error reporting by using swupdate command directly instead of sending
update files via IPC. Now errors during installation are correctly reported to
the script, and the state of failure is saved in U-Boot env, allowing the error
to be reported to the cloud. SWUpdate Suricatta state codes can be found at:
https://github.com/sbabic/swupdate/blob/master/include/suricatta/state.h
Additionally the 'last_install.log' log is now saved to the update files
folder, allowing to check what is the root cause of eventual problems.

Signed-off-by: Diego Rondini <diego.rondini@kynetics.com>

diff --git a/recipes-support/swupdate/swupdate-uf-installer-agent/swupdate-feeder b/recipes-support/swupdate/swupdate-uf-installer-agent/swupdate-feeder
--- a/recipes-support/swupdate/swupdate-uf-installer-agent/swupdate-feeder
+++ b/recipes-support/swupdate/swupdate-uf-installer-agent/swupdate-feeder
@@ -1,4 +1,40 @@
 #!/bin/sh
 
 source /etc/swupdate/swupdate.env
-swupdate-client /recovery/updates/*.swu && fw_setenv --script ${SWUPDATE_UBOOT_DIR}/installed.uenv && rm -rf /recovery/updates/*.swu && reboot
+
+exit_failure() {
+        echo "Installation of ${UPDATE_FILE} failed."
+        fw_setenv --script ${SWUPDATE_UBOOT_DIR}/install_failure.uenv
+        exit_reboot
+}
+
+exit_success() {
+        echo "Installation of updates succeeded."
+        fw_setenv --script ${SWUPDATE_UBOOT_DIR}/install_success.uenv
+        exit_reboot
+}
+
+exit_reboot() {
+        fw_setenv --script ${SWUPDATE_UBOOT_DIR}/update_finished.uenv
+        rm -f ${SWUPDATE_UPDATES_DIR}/*.swu
+        reboot
+        exit
+}
+
+
+UPDATE_FILES="$(find ${SWUPDATE_UPDATES_DIR}/ -name *.swu  -type f -maxdepth 1)"
+# Check if there are updates to install
+if [ -z "${UPDATE_FILES}" ]; then
+        echo "No update file to install."
+        exit_failure
+fi
+# There are updates to install; proceed
+for UPDATE_FILE in "${UPDATE_FILES}"; do
+        echo "Starting installation of ${UPDATE_FILE}"
+        swupdate -f /etc/swupdate/swupdate.cfg -i "${UPDATE_FILE}"
+        SWUPDATE_RESULT=$?
+        if [ $SWUPDATE_RESULT -ne 0 ]; then
+                exit_failure
+        fi
+done
+exit_success
